Fix redis multiprocess connection issue
- Seeing AttributeError: 'NoneType' object has no attribute 'readline'
- Have logger output to stdout
- Made alerter a class with the redis connection created in main_loop instead of global scope